language: r
sudo: false
cache: packages
dist: trusty

env:
  - R_PACKAGE=foobar3

r_github_packages:
  - MangoTheCat/goodpractice

after_success:
  - Rscript -e 'Sys.setenv(NOT_CRAN = "true"); x = goodpractice::gp(); z = paste0(capture.output(x), collapse="\\n"); cat(z, file = "summary.txt");  goodpractice::export_json(x, sprintf("ropensci_check_foobar3_%s.json", gsub(":|-", "_", format(Sys.time(), format="%y-%h-%d_%T")))); x'

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
    - $(git ls-files -o | grep -e '.txt' -e '.json' | tr "\n" ":")
