language: r
sudo: false
cache: packages
dist: trusty

env:
  matrix:
  - secure: myT6YTKDxRTIwFa4cuNQ7qQNIfCiEomra5N8FUH21+TDjdAL1bYzOMUMdBFlw1r38Vrj2+QkXvMdiMD2DCeqVrocxJCnA3eh+v531sq8fVyCy7fQrDflOu+pxA1aObfsHyP3srLnKdL+qAQNaDOiXKLYRMdYREiALJ58r7mTyFcUjnqEIg+XAofWmdSlsuNiRxPLGAwGpQhor4CL3CU2Q1tUUZFyOSogtWXzKsGTYwFRlZQC5Z3TDH+ilwJuP7Vaw6YwXYKvnf27rGne9asQ8EvGQqc6wycJ1OG5zSg0G8pJ1cTu3BqYstDe4b8L73qH9mD7CA3JBU+7NbiqtLWbA/PttER553zqV/8T9Es1poJKS6oW42hAIaRP1/sk6UVCLg+S8gMGD3qSEDJH9s2Q7ZwiE+lTHsiURnR3NJp+e0deSRuqsm1yE3JRoks7PNfz0JqSX52baEAbPKEjP+/n/9x9HFJGtO9Uhsa5REyKdIWRvT+QqgBgBWm1GYv0L1JwwUYQrvv2WeEs24/Erb2j+l0HlmE9HFNpwCOahAaEyHtO1zpslABlww6plbHjO9bQMRWQAvkzKoe4Njtk+tOEoUZlc6AAdfA5rIoBZ3rEKZUSZdvYAf8SGgibQKeAOGe6Oy8vT/jiXxLrIrKoV4tr9k+NdRceaWeGsr1gB80egoU=
  - secure: R0ZO08EDujp2gbY/2LBtnQttCbDsmJCdnVBvB+L8ju3u6th6iPP+adpaiy5c6G5uwNE3Z9Nij+oGxMAu6VMlH3mHqEGoOMYIrJgC0XeCr+/gpiALMXzKeLItruhLG5B/Ap3JDzAMYWCiEZWiq0I8yObZcbezm0y5KimB7FE8Lg5Xyb2ebgbn+z0oa6KvIz1v7gL2nbqDRIQ/T7eZSbXpj88Pvx7jj91iE99RPYr+9ZnjG6A5R/BP0Uz21hbVIyAek/z6dhy2pG5zhvuz9auH34PyT/ZPWoDcV53WpmSGu+P1jrtvgByj+i+ZUo5fom/xUsyfFfJKdZ3E2KWWifngmksYY635Me2gmEAloVsBXIqVpR2wpzDnCQOZQbnaqLgqoOgfKvq5tt6LI8cNOR8qFE7qsM8hLg9WPPUuCCS/nW2jkdWvlw9Z/mbtlVayQzcnZwH/JyrbCgQ4EwpJdkj1qaS1RzjAczKXV8nuJvZMNitlw1S0gwa4U8TdKZnzxDKDgeznIkJ+KSlcLyHj8ZHGjl/9G/mBEa32CplLp/ngsfCOqORBPigwKkkfKerwMWGwIPpq1I8UDISXmz1aD1vZQ5Bbk7SKsbmHrVKtlYONkv8+EBVkZWHLlLlC8fikQ0eRakLvwr+K1zBeAwiOGRz9tKNS4cpi/kgnltqW4rAM++8=
  - secure: yfq0bXAy/DKyIlvrm3ZJqj2m/r59iSYEAiUjWT8uE9LzaKGSzOoi1vJkicMwTsc81oi1V07p9YyQcXilwC1vv6YdVSynIrJgiqIuiCxyAC/7VBkSGR34tjNR//HUxxwTEGcyciy8kjpxa9c4G4w+4jzwgPVOpGw1Wv9YGoZlqml1XTOUh4Rw6fnxUKbjIUtDJVZL9900gTiOKTWEtI40yg7ycNbgJykSX/1Y16ys+6kUSBlzV5DpOVnH6V/he+cWPDpna45DX7Arm5cPpGWf/AW+O2cPXCSsx8Rmqj3JairBczmXoKjx7jsG23b2Xldh2Kz9dWp6MsklID5YC/ZWuOPraSIf71AEoKzGemVSLiahIUSqH7pGq5+udAalAZdvSQoHtYhotP7SJeGEHZ1Sxg0BI4mBqxrOtBI4rAAlFQX/xdtjvSTapADVtfXc+8kN6bNQ6FQXkPeoqNp4DzSB7PBERk9WbpEfpTZMPqA69+PqYP1rnkSms/00PkICtruOPfQpVl9oclQ7l04df4vyTXzyGrr1K/nPEJ3V35HTYJAkfXMFxadQ3Bh6XM59MDj28MXAzbNHngLhr2sCge+9sTK8lhZlT1GdwAOM24MjrXc1R9zt6Y81aZFdaE4V8LyDMfYbLPU1ENIXOXKg6lEfl4Rr9HFzSBkIwMzk4/JfhvU=

r_github_packages:
- MangoTheCat/goodpractice

after_success:
- Rscript -e 'Sys.setenv(NOT_CRAN = "true"); x = goodpractice::gp(); z = capture.output(x);
  pkg = x$package[[1]]; pkgver = x$description$get_version(); dt = gsub(":|-", "_",
  format(Sys.time(), format="%y-%h-%d_%T")); cat(z, file = sprintf("ropensci_check_%s_%s_%s.txt",
  pkg, pkgver, dt), sep = "\\n");  goodpractice::export_json(x, sprintf("ropensci_check_%s_%s_%s.json",
  pkg, pkgver, dt)); x'

addons:
  artifacts:
    s3_region: us-west-2
    paths:
    - $(git ls-files -o | grep -e '.txt' -e '.json' | tr "\n" ":")
